# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: bus_location.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12\x62us_location.proto\x12\x05proto\x1a\x1bgoogle/protobuf/empty.proto\";\n\x0b\x42usLocation\x12\x0b\n\x03lat\x18\x01 \x01(\x01\x12\x0c\n\x04long\x18\x02 \x01(\x01\x12\x11\n\ttimestamp\x18\x03 \x01(\x03\x32J\n\x12\x42usLocationService\x12\x34\n\x04Send\x12\x12.proto.BusLocation\x1a\x16.google.protobuf.Empty\"\x00\x42\x13Z\x11\x62us-project/protob\x06proto3')



_BUSLOCATION = DESCRIPTOR.message_types_by_name['BusLocation']
BusLocation = _reflection.GeneratedProtocolMessageType('BusLocation', (_message.Message,), {
  'DESCRIPTOR' : _BUSLOCATION,
  '__module__' : 'bus_location_pb2'
  # @@protoc_insertion_point(class_scope:proto.BusLocation)
  })
_sym_db.RegisterMessage(BusLocation)

_BUSLOCATIONSERVICE = DESCRIPTOR.services_by_name['BusLocationService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\021bus-project/proto'
  _BUSLOCATION._serialized_start=58
  _BUSLOCATION._serialized_end=117
  _BUSLOCATIONSERVICE._serialized_start=119
  _BUSLOCATIONSERVICE._serialized_end=193
# @@protoc_insertion_point(module_scope)
