# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: driver_fatigue.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x64river_fatigue.proto\x12\x05proto\x1a\x1bgoogle/protobuf/empty.proto\"5\n\x10\x46\x61tigueDetection\x12\x0e\n\x06status\x18\x01 \x01(\x05\x12\x11\n\ttimestamp\x18\x02 \x01(\x03\x32T\n\x17\x46\x61tigueDetectionService\x12\x39\n\x04Send\x12\x17.proto.FatigueDetection\x1a\x16.google.protobuf.Empty\"\x00\x42\x13Z\x11\x62us-project/protob\x06proto3')



_FATIGUEDETECTION = DESCRIPTOR.message_types_by_name['FatigueDetection']
FatigueDetection = _reflection.GeneratedProtocolMessageType('FatigueDetection', (_message.Message,), {
  'DESCRIPTOR' : _FATIGUEDETECTION,
  '__module__' : 'driver_fatigue_pb2'
  # @@protoc_insertion_point(class_scope:proto.FatigueDetection)
  })
_sym_db.RegisterMessage(FatigueDetection)

_FATIGUEDETECTIONSERVICE = DESCRIPTOR.services_by_name['FatigueDetectionService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\021bus-project/proto'
  _FATIGUEDETECTION._serialized_start=60
  _FATIGUEDETECTION._serialized_end=113
  _FATIGUEDETECTIONSERVICE._serialized_start=115
  _FATIGUEDETECTIONSERVICE._serialized_end=199
# @@protoc_insertion_point(module_scope)
