# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: seat_detection.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14seat_detection.proto\x12\x05proto\x1a\x1bgoogle/protobuf/empty.proto\"7\n\rSeatDetection\x12\x13\n\x0bseat_number\x18\x01 \x03(\x05\x12\x11\n\ttimestamp\x18\x02 \x01(\x03\x32N\n\x14SeatDetectionService\x12\x36\n\x04Send\x12\x14.proto.SeatDetection\x1a\x16.google.protobuf.Empty\"\x00\x42\x13Z\x11\x62us-project/protob\x06proto3')



_SEATDETECTION = DESCRIPTOR.message_types_by_name['SeatDetection']
SeatDetection = _reflection.GeneratedProtocolMessageType('SeatDetection', (_message.Message,), {
  'DESCRIPTOR' : _SEATDETECTION,
  '__module__' : 'seat_detection_pb2'
  # @@protoc_insertion_point(class_scope:proto.SeatDetection)
  })
_sym_db.RegisterMessage(SeatDetection)

_SEATDETECTIONSERVICE = DESCRIPTOR.services_by_name['SeatDetectionService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\021bus-project/proto'
  _SEATDETECTION._serialized_start=60
  _SEATDETECTION._serialized_end=115
  _SEATDETECTIONSERVICE._serialized_start=117
  _SEATDETECTIONSERVICE._serialized_end=195
# @@protoc_insertion_point(module_scope)
