FROM bde2020/spark-base:3.3.0-hadoop3.3

ENV SPARK_MASTER_NAME spark-master
ENV SPARK_MASTER_PORT 7077

EXPOSE 4040 8080 7077

WORKDIR '/app'

# Copy the source code
COPY ./configs/etl_config.json ./configs/etl_config.json
COPY ./jobs/j1939.dbc .
COPY ./jobs/iso.dbc .
COPY ./jobs/stream_job.py .
COPY packages.zip .

ENV SPARK_APPLICATION_PYTHON_LOCATION stream_job.py

COPY submit.sh /

CMD ["/bin/bash", "/submit.sh"]